version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
      
    working_directory: ~/repo

    steps:
      - checkout     
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
            sudo pip install flask 
      
        
      # run tests!
      - run:
          name: run tests
          command: |
            pipenv run python test.py
            pipenv run python getip.py
            
      - store_artifacts:
          path: test-reports
          destination: tr1